### ISSUE TITLE
Node client id generation discards 15 bits of timestamp

### ISSUE THREAD

**Issue by edible-programs** [tigerbeetle/tigerbeetle#3315]
The `>>>` operator discards all values greater than 2 ** 32  - 1. 15 bits of timestamp are lost as a result.

https://github.com/tigerbeetle/tigerbeetle/blob/a61a2af38e755a51a61f258cd9280e032613d5f0/src/clients/node/src/index.ts#L192

Though monotonicity is preserved, this should probably be fixed so timestamp extraction isn't broken.
A simple in-place fix would be to rewrite as follows:
```
idLastBuffer.setUint32(12, (timestamp / 0x10000) | 0, littleEndian)
```

**Comment by matklad** [comment]
What a catch, thanks!

**Comment by sentientwaffle** [comment]
Fixed by https://github.com/tigerbeetle/tigerbeetle/pull/3302

**Comment by matklad** [comment]
@sentientwaffle i think our JS code is still wrong here! Didn’t get to fixing it yet! I am overall not super happy how complicated our JS id generation is, I hope we can rewrite it without byte buffers.

Kudos to Rafael for noticing this!
